language: node_js
node_js: node
install: npm install
script: npm run build:dist
jobs:
  include:
  - stage: test
    script: npm run lint
  - script: npm test
  - stage: deploy
    deploy:
      provider: s3
      access_key_id: AKIAJZXTEI2P6XXOROOA
      secret_access_key:
        secure: qGm4GY4CMtOD8nTV7rMA7E9mFaN78xM8i1B/DiTrAtrpIl4xkE4eXSFvMacFGZta0O+m6wvsuKFBu71TmmeElbCvdkBCqalWSfI0ZoIA1DK2lOmkDZKvOiFJ7iHIqXfRbNmokeb2DTRv5YOP7c4RkifMUWBx/KJSCB0CkukhCmyWUJFn8KjO/lsdxzBFlhCWKCz8IkJ+p66+i1obvtwI1hw399OYCMiA0qEVHw80xaxRJEdzqOApKisglNvnI/roO5U3Uhe1XQk00Basd9iy0F1NlT7laiu6IxiQYTjEvXDlQUm4XH4+wqedafJlT+R6z2eb/HmeElsK41fUCX3vdPUHgeazp6Pe6wiGBsZxgGKWinh0/6wds97xU+/EQFh/JhsruVKJ6i3RiXwoSpR5VpoOqW5A96m+QICajcZgdAguhhEfXiRKxRsTrJKj5NgCl25xt4V2xEVy7N1mLZ2xSWZ2guGum/YFuA1IP2uUZwrf/qWyVc3jAVqZiPmObJez2VVJ/p8DWlpdsA1A7ylcA3JErTruvWp/vEmQgRc8ho63aBDyXH9GaTbBrGlfrD48Ssad5AMexvdmL6RYWTwlQG5fxvbGlUc2RZW3J0O/FJVkvLrdDQM830yc51Gg4fFft2ioo6a8hTyJ8ExyKbm9bj/aq+H8kYg2/lRDPmCY9LY=
      bucket: shermify
      local-dir: dist
      acl: public_read
      skip_cleanup: true
